version: '2'
services:
  commutedb:
    image: postgres:9.6
    environment:
      POSTGRES_DB: 'commutedb'
      POSTGRES_PASSWORD: 'commutedb'
      POSTGRES_USER: 'commutedb'
    ports:
      - 5432:5432
  #  volumes:
  #    - /var/lib/postgresql/data
  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
    environment:
        RABBITMQ_DEFAULT_USER: "commute"
        RABBITMQ_DEFAULT_PASS: "commute"
    ports:
     - 15672:15672
     - 5672:5672
  node-commute-api:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      PORT: 8080
      NODE_ENV: "production"
      MAILER_HOST: "smtp.gmail.com"
      MAILER_USER: "contato.danilo.paixao@gmail.com"
      MAILER_PASS: "$$password$$"
      MAILER_PORT: 465
      MAILER_SECURE: "true"
      DASHBOARD: "http://nginx:80"
      DB_HOSTNAME: commutedb
      DB_USERNAME: 'commutedb'
      DB_PASSWORD: 'commutedb'
      DB_NAME: 'commutedb'
      RABBITMQ_URL: "amqp://commute:commute@rabbitmq"
      # command: ["./node_modules/.bin/pm2-runtime", "server/index.js", "--watch"]
    ports:
      - 8080:8080
    #volumes:
    #    - ./server:/home/node/app
    depends_on: 
      - commutedb
      - rabbitmq
  